var annotated =
[
    [ "CGLA", null, [
      [ "TableTrigonometry", null, [
        [ "CosTable", "class_c_g_l_a_1_1_table_trigonometry_1_1_cos_table.html", "class_c_g_l_a_1_1_table_trigonometry_1_1_cos_table" ]
      ] ],
      [ "ArithMatFloat", "class_c_g_l_a_1_1_arith_mat_float.html", "class_c_g_l_a_1_1_arith_mat_float" ],
      [ "ArithQuat", "class_c_g_l_a_1_1_arith_quat.html", "class_c_g_l_a_1_1_arith_quat" ],
      [ "ArithSqMat2x2Float", "class_c_g_l_a_1_1_arith_sq_mat2x2_float.html", "class_c_g_l_a_1_1_arith_sq_mat2x2_float" ],
      [ "ArithSqMat3x3Float", "class_c_g_l_a_1_1_arith_sq_mat3x3_float.html", "class_c_g_l_a_1_1_arith_sq_mat3x3_float" ],
      [ "ArithSqMat4x4Float", "class_c_g_l_a_1_1_arith_sq_mat4x4_float.html", "class_c_g_l_a_1_1_arith_sq_mat4x4_float" ],
      [ "ArithSqMatFloat", "class_c_g_l_a_1_1_arith_sq_mat_float.html", "class_c_g_l_a_1_1_arith_sq_mat_float" ],
      [ "ArithVec", "class_c_g_l_a_1_1_arith_vec.html", "class_c_g_l_a_1_1_arith_vec" ],
      [ "ArithVec2Float", "class_c_g_l_a_1_1_arith_vec2_float.html", "class_c_g_l_a_1_1_arith_vec2_float" ],
      [ "ArithVec3Float", "class_c_g_l_a_1_1_arith_vec3_float.html", "class_c_g_l_a_1_1_arith_vec3_float" ],
      [ "ArithVec3Int", "class_c_g_l_a_1_1_arith_vec3_int.html", "class_c_g_l_a_1_1_arith_vec3_int" ],
      [ "ArithVec4Float", "class_c_g_l_a_1_1_arith_vec4_float.html", "class_c_g_l_a_1_1_arith_vec4_float" ],
      [ "ArithVec4Int", "class_c_g_l_a_1_1_arith_vec4_int.html", "class_c_g_l_a_1_1_arith_vec4_int" ],
      [ "ArithVecFloat", "class_c_g_l_a_1_1_arith_vec_float.html", "class_c_g_l_a_1_1_arith_vec_float" ],
      [ "ArithVecInt", "class_c_g_l_a_1_1_arith_vec_int.html", "class_c_g_l_a_1_1_arith_vec_int" ],
      [ "BitMask", "class_c_g_l_a_1_1_bit_mask.html", "class_c_g_l_a_1_1_bit_mask" ],
      [ "CGLAMotherException", "class_c_g_l_a_1_1_c_g_l_a_mother_exception.html", "class_c_g_l_a_1_1_c_g_l_a_mother_exception" ],
      [ "Mat2x2d", "class_c_g_l_a_1_1_mat2x2d.html", "class_c_g_l_a_1_1_mat2x2d" ],
      [ "Mat2x2f", "class_c_g_l_a_1_1_mat2x2f.html", "class_c_g_l_a_1_1_mat2x2f" ],
      [ "Mat2x3d", "class_c_g_l_a_1_1_mat2x3d.html", "class_c_g_l_a_1_1_mat2x3d" ],
      [ "Mat3x2d", "class_c_g_l_a_1_1_mat3x2d.html", "class_c_g_l_a_1_1_mat3x2d" ],
      [ "Mat2x3f", "class_c_g_l_a_1_1_mat2x3f.html", "class_c_g_l_a_1_1_mat2x3f" ],
      [ "Mat3x2f", "class_c_g_l_a_1_1_mat3x2f.html", "class_c_g_l_a_1_1_mat3x2f" ],
      [ "Mat3x3d", "class_c_g_l_a_1_1_mat3x3d.html", "class_c_g_l_a_1_1_mat3x3d" ],
      [ "Mat3x3f", "class_c_g_l_a_1_1_mat3x3f.html", "class_c_g_l_a_1_1_mat3x3f" ],
      [ "Mat4x4d", "class_c_g_l_a_1_1_mat4x4d.html", "class_c_g_l_a_1_1_mat4x4d" ],
      [ "Mat4x4f", "class_c_g_l_a_1_1_mat4x4f.html", "class_c_g_l_a_1_1_mat4x4f" ],
      [ "Quatd", "class_c_g_l_a_1_1_quatd.html", "class_c_g_l_a_1_1_quatd" ],
      [ "Quatf", "class_c_g_l_a_1_1_quatf.html", "class_c_g_l_a_1_1_quatf" ],
      [ "UnitVector", "class_c_g_l_a_1_1_unit_vector.html", "class_c_g_l_a_1_1_unit_vector" ],
      [ "Vec2d", "class_c_g_l_a_1_1_vec2d.html", "class_c_g_l_a_1_1_vec2d" ],
      [ "Vec2f", "class_c_g_l_a_1_1_vec2f.html", "class_c_g_l_a_1_1_vec2f" ],
      [ "Vec2i", "class_c_g_l_a_1_1_vec2i.html", "class_c_g_l_a_1_1_vec2i" ],
      [ "Vec2ui", "class_c_g_l_a_1_1_vec2ui.html", "class_c_g_l_a_1_1_vec2ui" ],
      [ "Vec3d", "class_c_g_l_a_1_1_vec3d.html", "class_c_g_l_a_1_1_vec3d" ],
      [ "Vec3f", "class_c_g_l_a_1_1_vec3f.html", "class_c_g_l_a_1_1_vec3f" ],
      [ "Vec3i", "class_c_g_l_a_1_1_vec3i.html", "class_c_g_l_a_1_1_vec3i" ],
      [ "Vec3uc", "class_c_g_l_a_1_1_vec3uc.html", "class_c_g_l_a_1_1_vec3uc" ],
      [ "Vec3usi", "class_c_g_l_a_1_1_vec3usi.html", "class_c_g_l_a_1_1_vec3usi" ],
      [ "Vec4d", "class_c_g_l_a_1_1_vec4d.html", "class_c_g_l_a_1_1_vec4d" ],
      [ "Vec4f", "class_c_g_l_a_1_1_vec4f.html", "class_c_g_l_a_1_1_vec4f" ],
      [ "Vec4i", "class_c_g_l_a_1_1_vec4i.html", "class_c_g_l_a_1_1_vec4i" ],
      [ "Vec4uc", "class_c_g_l_a_1_1_vec4uc.html", "class_c_g_l_a_1_1_vec4uc" ]
    ] ],
    [ "DSC", null, [
      [ "DeformableSimplicialComplex", "class_d_s_c_1_1_deformable_simplicial_complex.html", "class_d_s_c_1_1_deformable_simplicial_complex" ],
      [ "VelocityFunc", "class_d_s_c_1_1_velocity_func.html", "class_d_s_c_1_1_velocity_func" ]
    ] ],
    [ "is_mesh", null, [
      [ "util", "namespaceis__mesh_1_1util.html", "namespaceis__mesh_1_1util" ],
      [ "NodeAttributes", "classis__mesh_1_1_node_attributes.html", "classis__mesh_1_1_node_attributes" ],
      [ "EdgeAttributes", "classis__mesh_1_1_edge_attributes.html", "classis__mesh_1_1_edge_attributes" ],
      [ "FaceAttributes", "classis__mesh_1_1_face_attributes.html", "classis__mesh_1_1_face_attributes" ],
      [ "TetAttributes", "classis__mesh_1_1_tet_attributes.html", "classis__mesh_1_1_tet_attributes" ],
      [ "NodeIterator", "classis__mesh_1_1_node_iterator.html", "classis__mesh_1_1_node_iterator" ],
      [ "EdgeIterator", "classis__mesh_1_1_edge_iterator.html", "classis__mesh_1_1_edge_iterator" ],
      [ "FaceIterator", "classis__mesh_1_1_face_iterator.html", "classis__mesh_1_1_face_iterator" ],
      [ "TetrahedronIterator", "classis__mesh_1_1_tetrahedron_iterator.html", "classis__mesh_1_1_tetrahedron_iterator" ],
      [ "ISMesh", "classis__mesh_1_1_i_s_mesh.html", "classis__mesh_1_1_i_s_mesh" ],
      [ "kernel", "classis__mesh_1_1kernel.html", "classis__mesh_1_1kernel" ],
      [ "kernel_iterator", "classis__mesh_1_1kernel__iterator.html", "classis__mesh_1_1kernel__iterator" ],
      [ "Key", "classis__mesh_1_1_key.html", "classis__mesh_1_1_key" ],
      [ "NodeKey", "classis__mesh_1_1_node_key.html", "classis__mesh_1_1_node_key" ],
      [ "EdgeKey", "classis__mesh_1_1_edge_key.html", "classis__mesh_1_1_edge_key" ],
      [ "FaceKey", "classis__mesh_1_1_face_key.html", "classis__mesh_1_1_face_key" ],
      [ "TetrahedronKey", "classis__mesh_1_1_tetrahedron_key.html", "classis__mesh_1_1_tetrahedron_key" ],
      [ "Simplex", "classis__mesh_1_1_simplex.html", "classis__mesh_1_1_simplex" ],
      [ "Node", "classis__mesh_1_1_node.html", "classis__mesh_1_1_node" ],
      [ "Edge", "classis__mesh_1_1_edge.html", "classis__mesh_1_1_edge" ],
      [ "Face", "classis__mesh_1_1_face.html", "classis__mesh_1_1_face" ],
      [ "Tetrahedron", "classis__mesh_1_1_tetrahedron.html", "classis__mesh_1_1_tetrahedron" ],
      [ "SimplexSet", "classis__mesh_1_1_simplex_set.html", "classis__mesh_1_1_simplex_set" ],
      [ "Geometry", "classis__mesh_1_1_geometry.html", "classis__mesh_1_1_geometry" ],
      [ "MultipleGeometry", "classis__mesh_1_1_multiple_geometry.html", "classis__mesh_1_1_multiple_geometry" ],
      [ "Point", "classis__mesh_1_1_point.html", "classis__mesh_1_1_point" ],
      [ "Cube", "classis__mesh_1_1_cube.html", "classis__mesh_1_1_cube" ],
      [ "Cylinder", "classis__mesh_1_1_cylinder.html", "classis__mesh_1_1_cylinder" ],
      [ "Plane", "classis__mesh_1_1_plane.html", "classis__mesh_1_1_plane" ],
      [ "Circle", "classis__mesh_1_1_circle.html", "classis__mesh_1_1_circle" ],
      [ "Square", "classis__mesh_1_1_square.html", "classis__mesh_1_1_square" ]
    ] ],
    [ "parameters", "structparameters.html", "structparameters" ]
];